name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    env:
      SURGE_BASE_DOMAIN: sno2wman-hq-deploy-storybook-to-surge
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.1
          run_install: |
            - args: [--frozen-lockfile]
      - run: pnpm run storybook:build
      - run: pnpx --no-install surge ./storybook-static https://$SURGE_SUBDOMAIN.surge.sh  --token $SURGE_TOKEN
        if: ${{ github.event_name == 'push' }}
        env:
          SURGE_SUBDOMAIN: ${{ env.SURGE_BASE_DOMAIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      - run: pnpx --no-install surge ./storybook-static https://$(echo $SURGE_SUBDOMAIN | sed -e "s/\//-/").surge.sh  --token $SURGE_TOKEN
        if: ${{ github.event_name == 'pull_request' }}
        env:
          SURGE_SUBDOMAIN: ${{ env.SURGE_BASE_DOMAIN }}-${{ github.ref_name }}-${{ github.sha }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

