name: CI

on:
  push:
    branches:
      - "main"

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.1
          run_install: |
            - args: [--frozen-lockfile]
      - run: pnpm run storybook:build
      - run: pnpx --no-install surge ./storybook-static https://$SURGE_SUBDOMAIN.surge.sh  --token $SURGE_TOKEN
        env:
          SURGE_SUBDOMAIN: deploy-storybook-to-surge-sno2wman-hq
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

